### ISSUE TITLE
Pin Lock Feature

### ISSUE THREAD

**Issue by NightmindOfficial** [VICFR1TZ/linum#70]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
When the user starts the app and is logged in, the app will request a pin code if set by the user.
If the user forgets the pin code for some reason, he can trigger a special log out procedure on the pin code screen which will reset the pin code.
the pin is a 4-digit number.
the pin lock is inactive by default and has to be activated in the account screen.
the pin can be changed in the same account settings subsection

**Describe alternatives you've considered**
Biometrics (will be added in the far future)

**TASK LIST**

- [x] Create PIN screen with all relevant features
- [x] Add Logout Functionality which could reset the PIN
- [x] Create a special logout function (or parameter) which resets the pin (turns it off) @SoTBurst 
- [x] Create creation switcher (Tell the lock screen the purpose of the input: RECALL, CHANGE, INITIALIZE) which then determines the contents of the title and message strings
- [x] Create followup switcher (depending on the creation purpose mentioned above, decide what to do after the user completed the PIN query
- [x] #81
- [x] Create a lock screen state telling the user that the PIN was wrong
- [x] #82
- [x] get last login email address from sharedPreferences
- [x] #88
- [x] Integrate PIN query on app start-up
- [x] #97
- [x] call pinCodeProvider.resetSession(); if the app loses focus AND the user has the pin lock active
